wonderfulsoftware/webring

- index.html
Add notaboutcode.com to the webring
> Add notaboutcode.com

- index.html
> Add monosor.com & monosor.dev

- index.html
> Add chrisza.me

- index.html
kthxbai
Ref: https://github.com/unnawut/personal-site-v2/commit/58d97c9a236f3dc23cce54c46eab45acea9f5ca6
> Add unnawut.com

- index.html
Added the webring link to https://knowlats.dev/ 
The webring logo is on the top navigation of my website.
> Add knowlats.dev

- index.html
Hi. I'm hoping that this would be a great opportunity for us to connect and be inside the webring!
The logo of the webring is in the footer at the bottom of the page [petepittawat.dev](https://petepittawat.dev).
> Add petepittawat.dev

- index.html
Hi :wave: -add jojoee.com to the webring.
Thanks for the webring creation :smile:
> Add jojoee.com

- index.html
Just finished renovate my site once again :)
> chore: add rayriffy.com

- index.html
Added the webring link to https://kusumotolab.com
> Add kusumotolab.com

- index.html
> Add wiput.me

- index.html
Add [saltyaom.com](https://saltyaom.com) ~
> Add saltyaom.com

- index.html
Add [kykungz.dev](https://kykungz.dev) to webring. The webring icon is located in Navigation Bar.
> add kykungz.dev to webring

- index.html
Add [pandora.sh](https://pandora.sh) to webring. The ring is at the footer.
> Add pandora.sh

- index.html
icon positions in the bottom-right sidebar.
> Add poolsawat.com

- index.html
> Add Mymintrabbit.com ka 💕

- index.html
The webring icon is at bottom right in the footer.
> Add savepong.com

- index.html
Nice to see you all. 😄
The ring is on the sidebar.
> Add shayennn.com

- index.html
> Add jitrak.dev

- index.html
already put the webring link in the header & footer of https://www.varokas.com/
> Adds varokas.com

- index.html
* Added [somkiat.cc](https://www.somkiat.cc/) to webring
* Added logo on top of index page
> Add somkiat.cc to webring

- index.html
position for webring logo at header of website in desktop or at top of menu in mobile site
> Add mikkipastel.com

- index.html
The icon is in the navigation on both mobile and desktop.
> Add pontakorn.dev

- index.html
The icon is in the navigation bar.
Sorry, the domain is not my name but it's my personal blog. Is that ok?
> add wp.curve.in.th

- index.html
Webring icon at header logo website on desktop and mobile
> Add my website (adamblog) in webring

- index.html
Webring icon at the header on desktop and mobile
> Add curiousdev.in.th

- index.html
Hi! I have attached webring icon to my website.
> Add heyfirst.co to Webring

- index.html
> Add llun.me

- index.html
**Webring Position :** `Header`
> add t6tg.com site

- index.html
> Add mr.touno.io to webring

- index.html
> Add suam.wtf site

- index.html
Webring icon is next to text `Viva!`
> Add blog.oatto.dev site

- .vscode/settings.json
- index.html
ตำแหน่งของไอคอนบน Desktop และ Mobile บน https://toupawa.com อยู่ด้านบนขวานะครับ
> add toupawa.com

- index.html
ตำแหน่งของไอคอนบน Desktop และ Mobile บน https://blog.karnwong.me อยู่ซ้ายบนค่ะ
> add blog.karnwong.me

- index.html
Please add thiti.dev website
Desktop:
Mobile:
> Please add thiti.dev website

- index.html
webring link อยู่ซ้ายล่างครับผม
> add blog.kpping.me to webring list

- index.html
Webring icon at under my description on both mobile and desktop.
> add jungai.me to webring

- index.html
Add [bellmcp.work](https://bellmcp.work/) to webring. The webring icon is located at the footer section.
> Add bellmcp.work

- index.html
Hi, I want to add [jaruwat.fucking-thai.dev](https://jaruwat.fucking-thai.dev) to webring too!
This is my personal domain, but I shared it to my friends for using email.
If there is any problem with my domain name, please tell me. I can change it to another domain name for webring. ;w;
The webring icon is on top-right of website.
Sorry for my poor grammar. ;-;
> Add jaruwat.fucking-thai.dev

- index.html
> Add varkaria.tech to webring

- automation/e2e/cypress/integration/webring_integration.spec.js
> Fix failing Cypress test

- index.html
> webring cleanup on 2021-11-11

- index.html
Add https://heyfirst.co/rss.xml to `data-feed` on [heyfirst.co](https://heyfirst.co)
> Add data-feed to heyfirst.co

- index.html
> Add data-feed to jungai.me

- index.html
- index.js
To make it easier to see which site has new content, I am adding a **feed** to the webring’s website. The feed will appear below the main site list, which displays **one latest post** from that site.
Closes #53 
Closes #43
> Add feed to webring

- automation/e2e/cypress/integration/webring_e2e.spec.js
- automation/e2e/cypress/support/commands.js
- index.js
Intro is displayed as modal now.
> Improve onboarding UX

- index.html
Add https://t6tg.com/rss.xml to data-feed on t6tg.com
> feat: add data-feed to t6tg.com

- index.html
Could you please marge this commit for add rss of my website.
Thank you.
> feat: add new rss url for https://thiti.dev site

- index.html
I'm excited to be a part of this webring!
> Add `siriwatk.dev` to Webring

- index.html
Webring icon is located at the header.
> Add anuwatarvis.com

- index.html
* Adding [blog.yothinix.com](blog.yothinix.com) to the list in index.html
* Webring link/icon located on the right of top navigation bar
> Add blog.yothinix.com to the list

- index.html
- Add nitpum.com to a list in `index.html`
- Webring icon at a footer of the page beside social icons
> Add `nitpum.com` to Webring

- index.html
- Add mesodiar.com to a list in index.html
- link located in medium navigation
> :sparkles: Add mesodiar.com :koala:

- index.html
This is my personal website which I attach link on the right above the social media icon.
> 🙈 Add bigdatarpg.com 🐼

- index.html
I'm moving all the posts from https://monosor.com to https://garden.narze.live
> Migrate monosor.com to garden.narze.live

- automation/e2e/cypress/integration/webring.spec.js
> Refactor monosor.com to garden.narze.live in e2e test

- index.html
This is my personal website . I attach link on the right navigation bar.
> Add janescience.com  🔬

- index.html
url: https://garden.narze.live/index.xml
> Add rss feed to garden.narze.live

- index.html
> Add attomos.dev

- index.html
I attached webring on top right of navigation bar
> Add microbenz.in.th

- index.html
Link location : both desktop & mobile version are below the social bar
> Add gusbell.tech to webring 

- index.html
Location: Under Social Media Link
> add blog.nackie.party

- index.html
Webring icon on desktop and mobile is at the top left side of the page
> add tinarskii.com

- index.html
the icon is in the center, bottom of the blogger's name (kana2011th) 
and slightly altered the color a bit
> add blog.0002011.xyz to the ring

- index.html
Webring's icon is shown at the bottom right of page as fixed position and color of icon changed to be more green and just added rss feed.
> added katsuragi.detzz.in.th's rss feed

- index.html
> added patato.live to the ring

- index.html
Webring's icon is on the left side of the navigation bar (both desktop and mobile)
> added mirailisc.me to the ring

- index.html
Hi, I added the webring icon between the contact section and the footer of my portfolio https://th1nkk1d.xyz. Same for both desktop and mobile layouts.
> feat: Add th1nkk1d.xyz into the webring

- index.html
I added webring icon at the top right of hero section.  Same for website and mobile.
> Adding pawaret.dev to webring

- index.html
Webring icon on mobile and desktop is at the top left side of the page.
> added boonsong.dev to the ring

- index.html
Adding RSS feed to lucian.solutions
> add data-feed to lucian.solutions

- index.html
Link location: topmost on both desktop & mobile views.
> add poom.dev to webring

- index.html
I added webring icon at the top right of website and mobile
> add kajame.xyz to webring

- index.html
webring icons on top navbar both desktop and mobile screen.
> add 0xchai.io to webring

- index.html
I added webring icon at the footer 🙏
> Add devahoy to webring

- index.html
> update the new domain name

- index.html
I've joined this domain a long time ago, but there was a time when the web didn't work, now i'm up to date and use it.
> I need to join webring

- index.html
> add taoisaman.com to webring

- index.html
> add khet.tech to webring

- index.html
Add me.nsys.site to webring ✨😭
This is how it's look in PC
And in mobile
🥺🥺🥺
> add me.nsys.site to webring

- index.html
Hello, I want to add [maythiwat.com](https://maythiwat.com) to the webring 😄
**On Desktop**
Webring icon is on bottom right
**On Mobile**
Webring icon is on top right (under navbar)
> feat: add maythiwat.com

- index.html
> add pusanstudio.com to webring

- index.html
Hi !~ , I need to add [opecgame.in.th](https://www.opecgame.in.th) to webring 😭😭😭
Webring icon in navbar manu and Webring icon is rotating
around profile picture
> add: opecgame.in.th

- index.html
> add nayukikuu.xyz to webring

- index.html
- Webring is at upper-right corner
> Add yuttakhanb.dev to webring

- index.html
The webring link is in the partners section at the bottom of the homepage.
> Add yosiket.xyz to webring

- index.html
The webring link is in the contact section of the homepage
> Add pichy.dev to webring

- index.html
The icon is to the right of my logo.
Thanks.
> feat: add pinpong.co to webring

- index.html
The icon is to the right of website footer.
Thanks.
> feature add worathon.space to webring

- index.html
ตอนนี้เว็ปกำลังอยู่ในช่วงปรับปรุง ซึงอาจจะไม่อยู่ในเกณฑ์ของวงแหวนเว็บแล้ว
เลยจะขอเอาออกชั่วคราวก่อนจนกว่าเว็ปจะมีพอร์ตโฟลิโอ ผลงาน การแชร์ความรู้ต่างๆ หรือกลับมาอยู่ในเกณฑ์ของวงแหวนเว็บอีกครั้ง
ขอบคุณสำหรับ พื้นที่แห่งการแบ่งปันความรู้และนำเสนอผลงานครับ
> remove pusanstudio.com from webring temporary 

- index.html
Hi, I'd like to join the webring.
The webring icon is on my home card.
Thank you krub!
> Add phurit.de to webring

- index.html
the webring icon is located at the bottom right of the page
Mobile
Desktop
> add anuwong.com

- index.html
The webring icon/button is on the top banner of the page
> Add techtransthai.org

- index.html
> add:siravijbb.me to webring

- index.html
> Add profile.mwn99.com to webring

- index.html
> Add guitarpawat.me to webring

- index.html
**Description:**
This PR adds [thammarith.dev](https://thammarith.dev) to the Web Ring community.
The webring icon is located inside the footer of the page.
> Add thammarith.dev

- index.html
Webring Icon is in the footer krub
> Add nonthakon.com to webring

- index.html
- Add RSS Feed of yuttakhanb.dev
- Fix url of site. I've just migrated to Cloudflare
**Migrated site with webring**
**RSS feed**
> Add data-feed of yuttakhanb.dev site

- dashboard.html
This page lets me review all the sites in the webring. In previous years, I manually go through the sites to visit and take a quick review. I think having a dashboard page that helps detect common issues can help make this process faster.
Yearly cleanup coming soon, and with this tool, may be more frequent since the webring has been growing 😃
> add dashboard page

- index.html
> changed:Domain expired

- index.html
> webring cleanup on 2023-11-11

- index.html
from Siravijbb.me to .com in name
> small fix:.me to .com

- index.html
webring icon is here ✨
PC:
Mobile:
> add blog.codename-t.com to webring

- index.html
webring icon is here 
Desktop:
Mobile:
> add mikelopster.dev to webring

- index.html
Webring icon is on the navbar
| Platform | Screenshot (Light Mode) | Screenshot (Dark Mode)
| --- | --- | --- |
| Desktop |![image](https://github.com/wonderfulsoftware/webring/assets/85337926/2cadcc6e-4428-4a32-856d-f3167aabbd19) |  ![image](https://github.com/wonderfulsoftware/webring/assets/85337926/30c1488b-f66b-4973-be39-2be223b3616e) |
| Mobile | ![image](https://github.com/wonderfulsoftware/webring/assets/85337926/7689555b-e086-4430-87c9-b167aaef9b68) | ![image](https://github.com/wonderfulsoftware/webring/assets/85337926/e2771ff4-e0d1-4cb2-83a0-c8c4d2eaf102) |
> add blog.ninprd to webring

- index.html
Add webring icon to left buttom
> Add nicekun.dev to webring

- index.html
🌐 (index.html): Update website URL from khet.tech to khet.me for correct redirection
> update domain name kub

- index.html
The position of the icons on Desktop and Mobile are located on the Header menu of the website.
> Update index.html - add wawasabii.com to webring

- index.html
webring icon on desktop:
webring icon on mobile:
> add mos.ipt-group.xyz.com to webring

- index.html
webring icon on desktop:
webring icon on mobile:
> add faystarnext.studio to webring

- index.html
> add punn.dev to webring

- index.html
- Add feed.xml to punn.dev https://punn.dev/feed.xml
> Add data-feed for punn.dev

- index.html
ไอคอนวงแหวนอยู่ที่ส่วน navbar ของเว็บไซต์
> add satjawat.com to webring

- index.html
The icon is on the top right both mobile and desktop krub.
> add tachakorn.com

- index.html
I just notice my web does not have a feed there.
> Add feed for pontakorn.dev

- index.html
> add varkaria.works into webring

- index.html
Add mymoneytoolkit.app to webring
> Add mymoneytoolkit.app

- index.html
this is position on Desktop
this is position on mobile
> "Added codegeassmasterzeronebreakoutr1r2.code  to index.html"

- automation/e2e/playwright.config.ts
- automation/e2e/tests/webring.spec.ts
- index.html
> webring cleanup on 2024-11-11

- index.html
> Add blog.nattp.page

- index.html
> Add evarin.dev

- index.html
Hi there!
Could you please add https://phongsathorn.me/ to the webring. 
The webring icon is located in the footer of the site.
Thank you.
> Add phongsathorn.me

- index.html
> Add slamy.in.th

- index.html
> Add amiearth.com

- index.html
> Add mengsokool.space

- index.html
Webring's icon position: footer
> request for joining Webring

- index.html
ตำแหน่งของไอคอนบน Desktop และ Mobile
- page footer ครับ
> Add papazeal.com

- index.html
ตำแหน่งของไอคอนบน Desktop: อยู่บน navbar ครับ
ตำแหน่งของไอคอนบน Mobile: อยู่ข้างใน hamburger button ตรง navbar ครับ
> Add iamthana.com

- index.html
ตำแหน่งของไอคอนบน Desktop และ Mobile อยู่ตรง sidebar ด้านซ้ายบน
> Add chompukyrc.com

- index.html
Desktop: footer ขวาล่าง
Mobile: footer ขวาล่าง
> add supakorn.info

- index.html
- Update RSS feed URL for sujamess.com from `/rss` to `/rss.xml`
> Update RSS feed URL for sujamess.com

- index.html
Logo Webring ในเว็บไซต์ อยู่ header ของเว็บไซต์ ที่มุมขวาบน
> Add codekub.com

- index.html
Desktop:
-------------------------------------------------------------
Mobile:
> Add pattaramet.dev

- index.html
ตำแหน่งไอคอน web ring จะอยู่บริเวณ footer ด้านล่างครับ ทั้ง Desktop & Mobile
> Add blog.luckytime1996.dev

- index.html
ตำแหน่งของไอคอนอยู่ตรง Header ซ้ายบน ทั้ง Mobile และ Desktop ครับ
> Add knot-dev.me
