index.html

- The new link to `https://srakrn.me` on the page.
- The webring is on the upper left section of the web, as a part of the navigation menu.

Added srakrn.me

---

index.html

Add webring link to https://www.serial-coder.com/.
The webring logo is on the bottom of the front page.

add serial-coder.com

---

index.html

I write this pull request for adding my website to this webring.
The position of the webring logo is on the footer of my site as you can see in the below image
Mobile Display
Desktop Display

[ADD] GGolfz.codes

---

automation/site-fetcher/Dockerfile

This patch fixes a screenshot that cannot render emoji #46
- Add package [fonts-noto-color-emoji](https://packages.debian.org/buster/fonts-noto-color-emoji) support emoji font from Google
Test Screenshot

Fix: screenshot render emoji

---

automation/e2e/cypress/integration/webring_e2e.spec.js
automation/e2e/cypress/integration/webring_integration.spec.js

Hi @dtinth ,
I would like to submit E2E and add more test cases for Webring.
- e2e with real user behavior on a random link
- should navigate to the next link for n-link or last-link
- should navigate to the previous link for n-link or first-link
- should display the sticky consent banner
- should hide the sticky consent banner when it is clicked
- should contain a link on-site info section
- should return 200 for data.json
- should have keys for data.json
Feel free to change :smile:
Thanks

E2E: Add more test cases for Webring

---

index.html

ntsd.me domain is expired so I bought a new one
webrings are on the social link side tab and footer

fix: change ntsd.me to ntsd.dev

---

index.html

Link location: immediately before the footer on the landing page.

Added khong.xyz to the list

---

package.json
yarn.lock

As spectated in https://github.com/wonderfulsoftware/webring/pull/82#issuecomment-1024415464, the [feed-reader](https://github.com/ndaidong/feed-reader) package now release `5.0.0-rc3` which should fix the edge case.
Since I'm not familiar with node.js development, this PR only update the `package.json` file, while leaving `yarn.lock` untouched. Please consider updating the build environment.

Update feed-reader so it fix an edge case in #82

---

webring.animate_rot_friction.svg

The image will take more dimension up to 512x512 pixels in order to prevent the star being cropped out of the viewport on rotation. However, the star and ring will retain the same size of around 416x416 pixels (the whole image just need more "padding" spaces).
The keep the scale down ratio close to the original scale down (416px -> 32px), I'd suggest 512px -> 40px for this version.

Apply rotation animation to the ring

---

index.html

Icon is placed at the right-top corner of website on both desktop and mobile.

add nuttdam.com

---

index.html

Webring icon is placed at the footer of website on both desktop and mobile.

add blog.tawanchai.com

---

index.html

Webring's icon is shown at the bottom right of page as fixed position and color of icon changed to be more green.

added katsuragi.detzz.in.th

---

index.html

supratouch.dev is my personal portfolio website
the webring icon is at the top of the website, it fades it automatically after 2 seconds. both desktop and mobile view has the same icon position.

add: supratouch.dev

---

index.html

Webring icon (button) is at the social share section besides Twitter and Facebook

add lucian.solutions to webring

---

index.html

The webring icon is under my contact/social-media links in the `Contact Information` (the lower left box on desktop, the 2nd box on mobile) box.

Add mistertfy64.com to webring

---

index.html

> เป็นเว็บไซต์ส่วนตัว ไม่แสวงหากำไร
My website will break the rule, so I remove it because I plan to change from a personal blog to monetize with a membership and courses.
Thanks.

chore - remove devahoy due to planning to be monetization web

---

index.html

Webring icon is located at the top left navbar beside the webblog URL for both desktop and mobile screen krub.

add anewlife.dev to webring

---

index.html

Webring icon is located at the header on  either desktop or mobile.

✨ add tantatorn.xyz

---

index.html

Change rss feed link from medium to WordPress
link: https://mesodiar.com/
webring link is on the top right

:truck: Change rss feed from medium to wp

---

index.html

The webring position is at the top right of every page, located on the navbar

update `index.html` - add sujamess.com to webring

---

index.html

Greetings!
This PR adds zartre.com to the webring.
The Webring icon is placed just below the link section.

Add zartre.com

---

.github/workflows/e2e.yml

Fixes #230
Update the version of `actions/upload-artifact` in the E2E workflow file.
* Change the version of `actions/upload-artifact` from `v2` to `v4` in `.github/workflows/e2e.yml`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/wonderfulsoftware/webring/issues/230?shareId=636bcd31-87f7-49f8-95c7-5678b69b3f54).

Update upload-artifact action to v4 in E2E workflow

---

README.md
index.html

Fixes #228
Add Bluesky profile link to social media mentions
* Add a link to the Bluesky profile in the footer of `index.html`.
* Add a link to the Bluesky profile in the "โซเชียลเน็ตเวิร์ค" section of `README.md`.
* Mention that if you use your custom domains as a Bluesky handle, you will automatically be followed by our Bluesky account and added to the list of webring members on Bluesky, in Thai, in `README.md`.
* Use Markdown links instead of writing links separately in `README.md`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/wonderfulsoftware/webring/issues/228?shareId=d1da71e1-02e9-4eb2-9dff-394fa0530dc9).

Add link to Bluesky social
